# Generated by Django 5.2 on 2025-05-06 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('orders_completed', models.IntegerField(default=0)),
                ('total_delivery_time', models.DurationField(default=0)),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CourierVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True)),
                ('is_current', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_started', models.DateTimeField()),
                ('delivery_completed', models.DateTimeField(blank=True, null=True)),
                ('delivery_notes', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-delivery_started'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BICYCLE', 'Bicycle'), ('MOTORCYCLE', 'Motorcycle'), ('CAR', 'Car')], max_length=20)),
                ('model', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('plate_number', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
