# Generated by Django 5.2 on 2025-05-26 14:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierPerformance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('orders_completed', models.IntegerField(default=0, verbose_name='Выполнено заказов')),
                ('total_delivery_time', models.DurationField(default=0, verbose_name='Общее время доставки')),
                ('total_earnings', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий заработок')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Производительность курьера',
                'verbose_name_plural': 'Производительность курьеров',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='CourierVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущее назначение')),
            ],
            options={
                'verbose_name': 'Назначение транспорта',
                'verbose_name_plural': 'Назначения транспорта',
                'ordering': ['-assigned_date'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_started', models.DateTimeField(verbose_name='Время начала доставки')),
                ('delivery_completed', models.DateTimeField(blank=True, null=True, verbose_name='Время завершения доставки')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='Примечания к доставке')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Отчет о доставке',
                'verbose_name_plural': 'Отчеты о доставках',
                'ordering': ['-delivery_started'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('BICYCLE', 'Велосипед'), ('MOTORCYCLE', 'Мотоцикл'), ('CAR', 'Машина'), ('TRUCK', 'Грузовик')], max_length=20, verbose_name='Тип транспортного средства')),
                ('model', models.CharField(max_length=100, verbose_name='Модель')),
                ('color', models.CharField(max_length=50, verbose_name='Цвет')),
                ('plate_number', models.CharField(blank=True, max_length=20, verbose_name='Номер машины')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Активность')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Транспортное средство',
                'verbose_name_plural': 'Транспортные средства',
                'ordering': ['type', 'model'],
            },
        ),
    ]
