# Generated by Django 5.2 on 2025-05-18 17:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активность'),
        ),
    ]
