# Generated by Django 5.2 on 2025-05-18 12:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_initial'),
        ('orders', '0004_client_created_at_client_updated_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courierperformance',
            options={'ordering': ['-date'], 'verbose_name': 'Производительность курьера', 'verbose_name_plural': 'Производительность курьеров'},
        ),
        migrations.AlterModelOptions(
            name='couriervehicle',
            options={'ordering': ['-assigned_date'], 'verbose_name': 'Назначение транспорта', 'verbose_name_plural': 'Назначения транспорта'},
        ),
        migrations.AlterModelOptions(
            name='deliveryreport',
            options={'ordering': ['-delivery_started'], 'verbose_name': 'Отчет о доставке', 'verbose_name_plural': 'Отчеты о доставках'},
        ),
        migrations.AlterModelOptions(
            name='vehicle',
            options={'ordering': ['type', 'model'], 'verbose_name': 'Транспортное средство', 'verbose_name_plural': 'Транспортные средства'},
        ),
        migrations.AddField(
            model_name='courierperformance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='courierperformance',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='deliveryreport',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='courierperformance',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='courierperformance',
            name='date',
            field=models.DateField(verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='courierperformance',
            name='orders_completed',
            field=models.IntegerField(default=0, verbose_name='Выполнено заказов'),
        ),
        migrations.AlterField(
            model_name='courierperformance',
            name='total_delivery_time',
            field=models.DurationField(default=0, verbose_name='Общее время доставки'),
        ),
        migrations.AlterField(
            model_name='courierperformance',
            name='total_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Общий заработок'),
        ),
        migrations.AlterField(
            model_name='couriervehicle',
            name='assigned_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='couriervehicle',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='couriervehicle',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='Текущее назначение'),
        ),
        migrations.AlterField(
            model_name='couriervehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.vehicle', verbose_name='Транспортное средство'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='delivery_completed',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Время завершения доставки'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='delivery_notes',
            field=models.TextField(blank=True, verbose_name='Примечания к доставке'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='delivery_started',
            field=models.DateTimeField(verbose_name='Время начала доставки'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='orders.order', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='deliveryreport',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='logistics.vehicle', verbose_name='Транспортное средство'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='color',
            field=models.CharField(max_length=50, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активность'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(max_length=100, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='plate_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер машины'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='type',
            field=models.CharField(choices=[('BICYCLE', 'Велосипед'), ('MOTORCYCLE', 'Мотоцикл'), ('CAR', 'Машина'), ('TRUCK', 'Грузовик')], max_length=20, verbose_name='Тип транспортного средства'),
        ),
    ]
