# Generated by Django 5.2 on 2025-05-18 12:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +79999999999. От 9 до 20 цифр.', regex='^\\+?1?\\d{9,20}$')], verbose_name='Телефон'),
        ),
    ]
