# Generated by Django 5.2 on 2025-05-18 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(blank=True, verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('LOGISTICIAN', 'Логист'), ('COURIER', 'Курьер')], default='COURIER', max_length=20, verbose_name='Роль'),
        ),
    ]
