# Generated by Django 5.2 on 2025-05-18 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_customuser_address_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Администратор'), ('LOGISTICIAN', 'Логист'), ('COURIER', 'Курьер')], default='ADMIN', max_length=20, verbose_name='Роль'),
        ),
    ]
