# Generated by Django 5.2 on 2025-05-18 17:06

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=254, validators=[django.core.validators.EmailValidator()], verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Номер телефона должен быть в формате: +7XXXXXXXXXX', regex='^\\+?1?\\d{9,15}$')], verbose_name='Телефон'),
        ),
    ]
