# Generated by Django 5.2 on 2025-05-06 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('orders', '0003_alter_order_client_alter_order_courier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaddress',
            name='client',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientAddress',
        ),
    ]
