# Generated by Django 5.2 on 2025-05-18 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_alter_client_created_at_alter_client_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='address',
        ),
        migrations.CreateModel(
            name='ClientAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(verbose_name='Адрес')),
                ('is_default', models.BooleanField(default=False, verbose_name='Адрес по умолчанию')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Адрес клиента',
                'verbose_name_plural': 'Адреса клиентов',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
    ]
