# Generated by Django 5.2 on 2025-05-20 10:02

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_address_clientaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientaddress',
            name='address',
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='apartment',
            field=models.CharField(blank=True, max_length=20, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='courier_notes',
            field=models.TextField(blank=True, verbose_name='Комментарий для курьера'),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='house_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.RegexValidator(message='Почтовый индекс должен состоять из 6 цифр', regex='^\\d{6}$')], verbose_name='Почтовый индекс'),
        ),
        migrations.AddField(
            model_name='clientaddress',
            name='street',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата обновления профиля'),
        ),
    ]
