# Generated by Django 5.2 on 2025-05-18 16:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourierVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущее назначение')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата снятия с назначения')),
                ('courier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Курьер')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_vehicles', to='logistics.vehicle', verbose_name='Транспортное средство')),
            ],
            options={
                'verbose_name': 'Назначение транспорта',
                'verbose_name_plural': 'Назначения транспорта',
                'ordering': ['-assigned_at'],
                'unique_together': {('courier', 'vehicle')},
            },
        ),
    ]
