# Generated by Django 5.2 on 2025-05-26 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourierVehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_current', models.BooleanField(default=True, verbose_name='Текущее назначение')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения')),
                ('unassigned_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата снятия с назначения')),
            ],
            options={
                'verbose_name': 'Назначение транспорта',
                'verbose_name_plural': 'Назначения транспорта',
                'ordering': ['-assigned_at'],
            },
        ),
    ]
