# Generated by Django 5.2 on 2025-05-06 14:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('couriers', '0001_initial'),
        ('logistics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='couriervehicle',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_vehicles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='couriervehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_vehicles', to='logistics.vehicle'),
        ),
        migrations.AlterUniqueTogether(
            name='couriervehicle',
            unique_together={('courier', 'vehicle')},
        ),
    ]
