# Generated by Django 5.2 on 2025-05-18 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('couriers', '0002_initial'),
        ('logistics', '0003_alter_courierperformance_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='couriervehicle',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Назначение транспорта', 'verbose_name_plural': 'Назначения транспорта'},
        ),
        migrations.AlterField(
            model_name='couriervehicle',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата назначения'),
        ),
        migrations.AlterField(
            model_name='couriervehicle',
            name='courier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_vehicles', to=settings.AUTH_USER_MODEL, verbose_name='Курьер'),
        ),
        migrations.AlterField(
            model_name='couriervehicle',
            name='is_current',
            field=models.BooleanField(default=True, verbose_name='Текущее назначение'),
        ),
        migrations.AlterField(
            model_name='couriervehicle',
            name='unassigned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата снятия с назначения'),
        ),
        migrations.AlterField(
            model_name='couriervehicle',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courier_vehicles', to='logistics.vehicle', verbose_name='Транспортное средство'),
        ),
    ]
