# Generated by Django 5.2 on 2025-05-26 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Номер заказа')),
                ('order_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма заказа')),
                ('delivery_cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость доставки')),
                ('status', models.CharField(choices=[('NEW', 'Новый'), ('ASSIGNED', 'Назначен'), ('IN_PROGRESS', 'В процессе'), ('DELIVERED', 'Доставлен'), ('CANCELLED', 'Отменен')], db_index=True, default='NEW', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('delivery_date', models.DateField(db_index=True, verbose_name='Дата доставки')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарии')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='clients.client', verbose_name='Клиент')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
    ]
