# Generated by Django 5.2 on 2025-05-18 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_remove_client_address_clientaddress'),
        ('orders', '0002_alter_order_created_at_alter_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='clients.clientaddress', verbose_name='Адрес доставки'),
        ),
    ]
