# Generated by Django 5.2 on 2025-05-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_remove_clientaddress_address_clientaddress_apartment_and_more'),
        ('orders', '0003_alter_order_delivery_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='client_address',
            field=models.CharField(blank=True, max_length=255, verbose_name='Адрес клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='ФИО клиента'),
        ),
        migrations.AddField(
            model_name='order',
            name='client_phone',
            field=models.CharField(blank=True, max_length=32, verbose_name='Телефон клиента'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='clients.client', verbose_name='Клиент'),
        ),
    ]
